bitbucket:
  slug: nimbl3/filestack-rails-storage-web
  username: [EMAIL]
  password: [PASSWORD]
  web_endpoint: https://bitbucket.org/
max_warnings: 150
verbose: true
format: "[%{runner}]-[%{level}]-%{msg}"
